services:
  qbittorrent-nox:
    # for debugging
    #cap_add:
      #- SYS_PTRACE
    environment:
      #- PAGID=10000
      - PGID=1000
      - PUID=1000
      - QBT_LEGAL_NOTICE=confirm
      - QBT_WEBUI_PORT=9977
      - TZ=Europe/Copenhagen
      #- UMASK=022
    image: ghcr.io/qbittorrent/docker-qbittorrent-nox:5.0.5-1
    ports:
      # for bittorrent traffic
      - 6881:6881/tcp
      - 6881:6881/udp
      # for WebUI
      - 9977:8080/tcp
    read_only: false
    stop_grace_period: 30m
    tmpfs:
      - /tmp
    tty: true
    volumes:
      - ./data:/config
      - /vault:/vault:rw
      - /vault2:/vault2:rw
