services:
  wgeasy:
    container_name: wgeasy
    hostname: wgeasy
    image: ghcr.io/wg-easy/wg-easy:15.0.0-beta.10
    env_file: .env
    restart: unless-stopped
    volumes:
      - ./data/wgeasy:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    ports:
      - 51820:51820/udp
      - 51821:51821/tcp
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.default.forwarding=1
    networks:
      wgeasy:
        ipv4_address: 10.8.1.5

  pihole-unbound:
    container_name: pihole-unbound
    hostname: pihole
    domainname: pihole.local
    image: ghcr.io/mpgirro/docker-pihole-unbound:2025.03.1
    env_file: .env
    restart: unless-stopped
    environment:
      TZ: Europe/Copenhagen
      FTLCONF_LOCAL_IPV4: ${FTLCONF_LOCAL_IPV4}
      WEBPASSWORD: ${PIHOLE_PASS}
      WEBTHEME: default-dark
      REV_SERVER: "true"
      REV_SERVER_TARGET: ${REV_SERVER_TARGET}
      REV_SERVER_DOMAIN: ${REV_SERVER_DOMAIN}
      REV_SERVER_CIDR: ${REV_SERVER_CIDR}
      PIHOLE_DNS_: 127.0.0.1#5335
      DNSSEC: "true"
      DNSMASQ_LISTENING: "all"
    volumes:
      - ./data/pihole/etc_pihole-unbound:/etc/pihole:rw
      - ./data/pihole/etc_pihole_dnsmasq-unbound:/etc/dnsmasq.d:rw
    ports:
      - 444:443/tcp
      - 53:53/tcp
      - 53:53/udp
      - 8080:80/tcp #Allows use of different port to access pihole web interface when other docker containers use port 80
      - 5335:5335/tcp # Uncomment to enable unbound access on local server
    networks:
      wgeasy:
        ipv4_address: 10.8.1.3

networks:
  wgeasy:
    ipam:
      config:
        - subnet: 10.8.1.0/24
