services:
    g4f:
        ports:
            - 50431:8080
            - 7900:7900
        shm_size: 2g
        volumes:
            - ./data/har_and_cookies:/app/har_and_cookies
            - ./data/generated_images:/app/generated_images
        restart: unless-stopped
        image: hlohaus789/g4f:0.5.3.1

