services:
    lms:
        image: ghcr.io/lms-community/lyrionmusicserver:9.0.3
        volumes:
            - ./data:/config:rw
            - /vault/Audio/Music/:/music:ro
            - /vault/Audio/Playlists/:/playlist:rw
        ports:
            - "9000:9000"
            - "9090:9090"
            - "3483:3483/udp"
            - "3483:3483/tcp"
