[hosts.desktop-wsl]
desc = "Desktop gaming computer"
hostName = "mads-desktop"
ipAddress = "192.168.0.146"

[hosts.server-nixos]
desc = "Rack-server for homelab"
hostName = "mads-server"
ipAddress = "192.168.0.69"

[hosts.laptop-wsl]
desc = "Primary laptop"
hostName = "mads-laptop"
ipAddress = ""

[hosts.laptop2-nixos]
desc = "Secondary laptop (a bit shit)"
hostName = "mads-laptop2"
ipAddress = ""

[hosts.pi-nixos]
desc = "Raspberry Pi 3b"
hostName = "mads-pi"
ipAddress = ""
