services:
  cloudflare-ddns:
    container_name: cloudflare-ddns
    hostname: cloudflare-ddns.local
    image: docker.io/timothyjmiller/cloudflare-ddns:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
        TZ: Europe/Copenhagen
        PUID: 1000
        PGID: 1000
    volumes:
      - ./data/config.json:/config.json:ro
    network_mode: "host"
