services:
  cloudflare-ddns:
    container_name: cloudflare-ddns
    hostname: cloudflare-ddns.local
    image: docker.io/timothyjmiller/cloudflare-ddns:latest
    env_file: .env
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
        TZ: Europe/Copenhagen
        PUID: 1000
        PGID: 1000
    volumes:
      - ./config/config.json:/config.json:ro
    network_mode: "host"
