services:
  mc:
    image: ghcr.io/itzg/minecraft-server:java21
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      VERSION: "1.21.4"
      MEMORY: "8G"
      TYPE: "FABRIC"
      MODRINTH_PROJECTS: "fabric-api,cloth-config,ferrite-core,lithium,fabric-language-kotlin,yacl,modernfix,collective,krypton,debugify,clumps,owo-lib,better-stats,skinshuffle,improved-signs"
      MODRINTH_DOWNLOAD_DEPENDENCIES: "required"
      MODRINTH_ALLOWED_VERSION_TYPE: "alpha"
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./data:/data
