services:
  mc:
    image: ghcr.io/itzg/minecraft-server:java21
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      VERSION: "1.21.7"
      MEMORY: "16G"
      VIEW_DISTANCE: "32"
      DIFFICULTY: "normal"
      MOTD: "Mads' Single Player (glitchless)"
      ICON: "server-icon.png"
      OVERRIDE_ICON: true
      FORCE_GAMEMODE: true
      MAX_PLAYERS: "1"
      SNOOPER_ENABLED: false
      LEVEL: "world"
      ONLINE_MODE: true
      SERVER_NAME: "Mads' Single Player (glitchless)" 
      TYPE: "FABRIC"
      MODRINTH_PROJECTS: "fabric-api,ferrite-core,lithium,simple-voice-chat,better-stats,skinshuffle,improved-signs,tcdcommons,c2me-fabric,krypton"
      MODRINTH_DOWNLOAD_DEPENDENCIES: "required"
      MODRINTH_ALLOWED_VERSION_TYPE: "alpha"
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./data:/data
