services:
  dash:
    image: mauricenino/dashdot:nvidia
    restart: unless-stopped
    privileged: true
    #deploy:
    #  resources:
    #    reservations:
    #      devices:
    #        - capabilities:
    #            - gpu
    ports:
      - "3001:3001"
    #devices:
    #  - nvidia.com/gpu=all
    volumes:
      - /:/mnt/host:ro
      - /vault:/vault:ro
    environment:
      - DASHDOT_WIDGET_LIST=os,cpu,storage,ram,network
      - DASHDOT_ALWAYS_SHOW_PERCENTAGES=true
      - DASHDOT_OS_LABEL_LIST=os,arch,up_since,dash_version
      - DASHDOT_SHOW_HOST=true
      - DASHDOT_OVERRIDE_OS=NixOS 24.11
      - DASHDOT_ENABLE_CPU_TEMPS=true
      - DASHDOT_OVERRIDE_CPU_BRAND=Intel
      - DASHDOT_OVERRIDE_CPU_MODEL=Xeon X5647
