system:
    configured_version: 0.10.1
    timezone: Europe/Copenhagen
    card_enabled: true
    cal_enabled: true
    dav_auth_type: Digest
    admin_passwordhash: 09707198ae4c830c207f750c79c5bc1f72902017aa119daa266dc31bea71ecee
    failed_access_message: 'user %u authentication failure for Baikal'
    auth_realm: BaikalDAV
    base_uri: ''
    invite_from: ''
database:
    sqlite_file: /var/www/baikal/Specific/db/db.sqlite
    backend: sqlite
    mysql_host: ''
    mysql_dbname: ''
    mysql_username: ''
    mysql_password: ''
    encryption_key: c8deec3f8b31677fa6ede8e3c8c018ec
    pgsql_host: ''
    pgsql_dbname: ''
    pgsql_username: ''
    pgsql_password: ''
