services:
  jdownloader2:
    image: ghcr.io/jlesage/jdownloader-2:v25.02.1
    restart: unless-stopped
    ports:
      - "50438:5800"
    volumes:
      - "./data:/config:rw"
      - "/home/mads/Downloads:/Downloads:rw"
      - "/vault:/vault:rw"
      - "/vault2:/vault2:rw"
    environment:
      - DARK_MODE=1
