services:
  vaultwarden:
    image: vaultwarden/server:1.34.1
    container_name: vaultwarden
    restart: always
    environment:
      DOMAIN: "https://vault.l.zzzealed.com"  # required when using a reverse proxy; your domain; vaultwarden needs to know it's https to work properly with attachments
      SIGNUPS_ALLOWED: "false" # Deactivate this with "false" after you have created your account so that no strangers can register
    volumes:
      - ./data:/data # the path before the : can be changed
    ports:
      - 50847:80 # you can replace the 11001 with your preferred port
