theme:
  # default (light)
  light: true
  background-color: 0 0 90
  primary-color: 120 100 50
  positive-color: 120 100 50
  negative-color: 0 70 70
  contrast-multiplier: 1.3

  disable-picker: false

  presets:
    default-dark:
      light: false
      background-color: 220 15 15
      primary-color: 120 100 50
      positive-color: 120 100 50
      negative-color: 0 70 70
      contrast-multiplier: 1.3

pages:
  - $include: page1.yml
  - $include: page2.yml
  - $include: page3.yml
