theme:
  background-color: 220 15 15
  primary-color: 120 100 50
  contrast-multiplier: 1.1

pages:
  - name: Home
    columns:
      - size: small
        widgets:
          - type: calendar

          - type: monitor
            cache: 1m
            title: Selfhosted
            sites:
              - title: Vaultwarden
                url: https://vault.l.zzzealed.com
                icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/vaultwarden.svg
              - title: Pihole
                url: https://pihole.l.zzzealed.com/admin
                icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/pi-hole.svg
              - title: GPT4Free
                url: https://gpt4free.l.zzzealed.com/chat
                icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/chatgpt.svg
              - title: JDownloader2
                url: https://jd2.l.zzzealed.com
                icon: https://cdn.jsdelivr.net/gh/selfhst/icons/webp/jdownloader.webp
              - title: qBittorrent
                url: https://qbit.l.zzzealed.com
                icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/qbittorrent.svg
              - title: WG-Easy
                url: https://wg.l.zzzealed.com
                icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/wireguard.svg
              - title: HomeAssistant
                url: http://server.l.zzzealed.com:8123
                icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/home-assistant.svg
              - title: Scrutiny
                url: https://scrutiny.l.zzzealed.com
                icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/scrutiny.svg
                            
          - type: twitch-channels
            title: Twitch
            channels:
              - RetalsRL
              - atowwwww
              - Vatira_
              - dralii
              - itachi_rl
              - RocketLeague
              - RLEsports
              - ow_esports
              - oilrats

      - size: full
        widgets:
          - type: rss
            title: News
            style: horizontal-cards
            feeds:
              - url: https://www.theguardian.com/us/rss
              - title: The Guardian news

          - type: rss
            title: Culture
            style: horizontal-cards
            feeds:
              - url: https://www.wired.com/feed/category/culture/latest/rss
              - title: WIRED culture

              - url: https://www.theverge.com/entertainment/rss/index.xml
              - title: The Verge entertainment

              - url: https://arstechnica.com/gaming/rss
              - title: Ars Technica gaming

              - url: https://mashable.com/feeds/rss/entertainment
              - title: Mashable entertainment

              - url: https://www.polygon.com/rss/index.xml
              - title: Polgyon gaming

          - type: rss
            title: Linux & Selfhosted
            style: horizontal-cards
            feeds:
              - url: https://itsfoss.com/rss
              - title: It's FOSS

              - url: https://noted.lol/rss/
              - title: noted.lol

              - url: https://selfh.st/rss/
              - title: selfh.st

          - type: rss
            title: Tech
            style: horizontal-cards
            feeds:
              - url: https://www.theverge.com/tech/rss/index.xml
              - title: The Verge tech

              - url: https://arstechnica.com/gadgets/rss
              - title: Ars Techinca tech

              - url: https://mashable.com/feeds/rss/tech
              - title: Mashable tech

              
          - type: videos
            title: YouTube
            channels:
              - UCRLM6B6rGXDSJawUH_mHHPw # Retals
              - UC5UAwBUum7CPN5buc-_N1Fw # The Linux Experiment
              - UClCNSSL0q1TafS8kaYEAwew # NFR Podcast
              - UCE_BYUUN0I04cAmk1c40sTg # Tesla
              - UCj-wTLj0p0YvTkS-9-ACm0A # Blooprint
              - UCiflacceDTPX3_SJG3Uiqkg # Motion
              - UCtQ3NfmlxDDWyhfxxgOsJhA # Frost
              - UCj25EgqxLL4HlUYkug7duig # Stevie
              - UC1DTYW241WD64ah5BFWn4JA # Sam O'Nella
              - UCTSRIY3GLFYIpkR2QwyeklA # Drew Gooden
              - UCFQMnBA3CS502aghlcr0_aw # CoffeeZilla
              - UCVWhVAZwCdQsPZL-mDLcxPQ # Whitelight
              - UC7Ucs42FZy3uYzjrqzOIHsw # EmpLemon
              - UCYGDiVemmhY_Q1M-hKp4fvw # bigboss
              - UCRbOPaGDB_xOQkVM8Rnn62Q # IHE
              - UC2C_jShtL725hvbm1arSV9w # CGP Grey
              - UC3cpN6gcJQqcCM6mxRUo_dA # Wendigoon
              - UCpFFItkfZz1qz5PpHpqzYBw # Nexpo

      - size: small
        widgets:
          - type: clock
            hour-format: 24h
          
          - type: weather
            location: Aarhus, Denmark
            
          - type: markets
            markets:
              - symbol: SPY
                name: S&P 500
              - symbol: BTC-USD
                name: Bitcoin
              - symbol: NVDA
                name: NVIDIA
              - symbol: AAPL
                name: Apple
              - symbol: MSFT
                name: Microsoft
              - symbol: GOOGL
                name: Google
              - symbol: AMD
                name: AMD
              - symbol: RDDT
                name: Reddit

