services:
  jackett:
    image: ghcr.io/linuxserver/jackett:0.22.2017
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Copenhagen
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - ./data:/config
      - /vault/Documents/Torrents:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
