---
http:
  # -- Change Router Configuration here...
  routers:
    jdownloader2:
      rule: "Host(`jd2.l.zzzealed.com`)"  # <-- Change Rules here...
      service: jdownloader2  # <-- Change Service Name here...
      priority: 1000  # <-- (Optional) Change Routing Priority here...
      entryPoints:
        - web
        - websecure
      tls:
        certResolver: cloudflare

  # -- Change Service Configuration here...
  services:
    jdownloader2:  # <-- Change Service Name here...
      loadBalancer:
        servers:
          - url: "http://192.168.0.118:5800"  # <-- Change Target Service URL here...
