---
http:
  # -- Change Router Configuration here...
  routers:
    searxng:
      rule: "Host(`searxng.l.zzzealed.com`)"  # <-- Change Rules here...
      service: searxng  # <-- Change Service Name here...
      priority: 1000  # <-- (Optional) Change Routing Priority here...
      entryPoints:
        - web
        - websecure
      tls:
        certResolver: cloudflare

  # -- Change Service Configuration here...
  services:
    searxng:  # <-- Change Service Name here...
      loadBalancer:
        servers:
          - url: "http://server.l.zzzealed.com:8072"  # <-- Change Target Service URL here...
