theme = "doom_acario_dark"

[editor]
line-number = "relative"
bufferline = "multiple"
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "read-only-indicator", "version-control"]
center = ["file-name", "file-modification-indicator"]
right = ["spinner", "position"]

[editor.gutters]
layout = ["line-numbers", "spacer", "diff"]

#[keys.normal]
#C-y = [
#  ':sh rm -f /tmp/unique-file',
#  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
#  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
#  ':open %sh{cat /tmp/unique-file}',
#  ':redraw',
#]
