services:
  makemkv:
    image: ghcr.io/jlesage/makemkv:v25.04.1
    ports:
      - "50017:5800"
    volumes:
      - "./data:/config:rw"
      - "/vault2:/vault2:rw"
#    devices:
#      - "/dev/sr0:/dev/sr0"
#      - "/dev/sg2:/dev/sg6"
